import { GoogleEcosystemWebsite } from '../types';

export const DEFAULT_PUBLISHER_ID = 'ca-pub-9842103857192841';
export const DEFAULT_GOOGLE_ADS_ID = 'AW-11482910482';

export const generateAdsTxtContent = (publisherId: string): string => {
  const sanitizedPub = publisherId.replace(/^ca-/, '').trim();
  return [
    '# =========================================================================',
    '# ads.txt - Authorized Digital Sellers',
    '# Standardized according to IAB Tech Lab Ads.txt Specification',
    '# =========================================================================',
    `google.com, ${sanitizedPub || 'pub-XXXXXXXXXXXXXXXX'}, DIRECT, f08c47fec0942fa0`,
    '',
  ].join('\n');
};

export const generateMetaVerification = (publisherId: string): string => {
  return `<meta name="google-adsense-account" content="${publisherId || 'ca-pub-XXXXXXXXXXXXXXXX'}">`;
};

export const generateAdSenseScript = (publisherId: string): string => {
  return `<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${publisherId || 'ca-pub-XXXXXXXXXXXXXXXX'}" crossorigin="anonymous"></script>`;
};

export const generateGoogleTagSnippet = (googleTagId: string): string => {
  const tag = googleTagId || 'AW-XXXXXXXXXX';
  return `<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=${tag}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', '${tag}');
</script>`;
};

export const INITIAL_9_WEBSITES_CONFIG: GoogleEcosystemWebsite[] = [
  {
    id: 1,
    domainPlaceholder: '[DOMAIN 1]',
    activeDomain: 'muneeb-lime.vercel.app',
    siteName: 'Shaheen Al Zaitoon Online Quran Academy',
    siteNameUrdu: 'شاہین الزیتون آن لائن قرآن اکیڈمی (مرکزی پورٹل)',
    tagline: 'Global 1-on-1 Online Quran & Tajweed Academy',
    category: 'Islamic Education & Quranic Studies',
    description: 'Premier online academy offering 1-on-1 personalized Quran reading, Tajweed, Noorani Qaida, and Hifz classes for kids, ladies, and adults worldwide.',
    publisherId: DEFAULT_PUBLISHER_ID,
    googleTagId: DEFAULT_GOOGLE_ADS_ID,
    adsTxtContent: generateAdsTxtContent(DEFAULT_PUBLISHER_ID),
    verificationMetaTag: generateMetaVerification(DEFAULT_PUBLISHER_ID),
    adsEnabled: true,
    adSenseStatus: 'Ready for Review',
    googleAdsStatus: 'Active Tracking',
    checklist: {
      domainConnected: true,
      httpsActive: true,
      adSenseTechnicalReady: true,
      publisherIdReady: true,
      adsTxtReady: true,
      verificationReady: true,
      responsiveAdPlacementsReady: true,
      googleAdsTrackingReady: true,
      seoStructureChecked: true,
      privacyTermsCookiesChecked: true,
      mobileResponsivenessChecked: true,
      performanceChecked: true,
      securityChecked: true,
      deploymentChecked: true,
    },
    adSlots: [
      {
        slotId: 'ad-slot-header-leaderboard',
        name: 'Header Top Leaderboard',
        nameUrdu: 'اوپری ہیڈر بینر',
        format: 'horizontal-banner',
        dimensions: 'Responsive (728x90 desktop / 320x50 mobile)',
        accidentalClickProtected: true,
        labeledAdvertisement: true,
        recommendedPosition: 'Below navigation bar with 24px safety margin',
      },
      {
        slotId: 'ad-slot-course-in-article',
        name: 'In-Article Course Content Unit',
        nameUrdu: 'کورس مواد کے درمیان اشتہار',
        format: 'in-article',
        dimensions: 'Responsive (Fluid width, min-height 250px)',
        accidentalClickProtected: true,
        labeledAdvertisement: true,
        recommendedPosition: 'Between course syllabus and enrollment perks',
      },
      {
        slotId: 'ad-slot-sidebar-display',
        name: 'Portal & Blog Sidebar Display',
        nameUrdu: 'سائیڈ بار ڈسپلے اشتہار',
        format: 'sidebar',
        dimensions: '300x250 or 300x600 Half Page',
        accidentalClickProtected: true,
        labeledAdvertisement: true,
        recommendedPosition: 'Sticky sidebar below student announcements',
      },
      {
        slotId: 'ad-slot-footer-multiplex',
        name: 'Footer Related Content Multiplex',
        nameUrdu: 'فوٹر ملٹی پلیکس گرڈ',
        format: 'responsive',
        dimensions: 'Responsive Grid (Matched Content style)',
        accidentalClickProtected: true,
        labeledAdvertisement: true,
        recommendedPosition: 'Above footer links with distinct border separator',
      },
    ],
    conversionGoals: [
      {
        name: 'Admission / 3-Day Free Trial Enrollment',
        category: 'Lead',
        eventName: 'enrollment_submission',
        sendTo: `${DEFAULT_GOOGLE_ADS_ID}/enr_lead_98`,
        status: 'Active',
        trigger: 'Triggered upon completing enrollment modal form submission',
      },
      {
        name: 'Official WhatsApp Click & Chat',
        category: 'Contact',
        eventName: 'whatsapp_contact_click',
        sendTo: `${DEFAULT_GOOGLE_ADS_ID}/wa_chat_42`,
        status: 'Active',
        trigger: 'Triggered when visitors tap WhatsApp widget or call links',
      },
      {
        name: 'EasyPaisa Fee Receipt Upload',
        category: 'Purchase',
        eventName: 'fee_payment_slip_uploaded',
        sendTo: `${DEFAULT_GOOGLE_ADS_ID}/fee_pay_19`,
        status: 'Active',
        trigger: 'Triggered upon uploading fee confirmation voucher on Fee Payment page',
      },
    ],
    missingRequirements: [
      'Submit domain to your Google AdSense console for final domain verification crawler crawl.',
    ],
    requiredGoogleAction: 'Login to Google AdSense (https://adsense.google.com) > Sites > Add Site > Enter your domain > Submit for review.',
    requiredAIStudioAction: 'Technical architecture, ads.txt endpoint, verification meta, responsive ad placements, privacy/cookie policy, and conversion hooks fully deployed.',
    deploymentStatus: 'Deployed & Active',
  },
  {
    id: 2,
    domainPlaceholder: '[DOMAIN 2]',
    activeDomain: 'zaitoon-traders.shaheenedu.com',
    siteName: 'ZT (Zaitoon Traders) - Halal E-Commerce',
    siteNameUrdu: 'زیتون ٹریڈرز (حلال ای کامرس اور عجوہ کھجوریں)',
    tagline: 'Authentic Madina Ajwa Dates, Sidr Honey, Royal Ittars & Rehal',
    category: 'Halal E-Commerce & Sunnah Products',
    description: 'Digital retail and wholesale store offering authentic Saudi Ajwa dates, Sidr honey, alcohol-free Islamic fragrances, digital Quran read pens, and prayer accessories.',
    publisherId: DEFAULT_PUBLISHER_ID,
    googleTagId: DEFAULT_GOOGLE_ADS_ID,
    adsTxtContent: generateAdsTxtContent(DEFAULT_PUBLISHER_ID),
    verificationMetaTag: generateMetaVerification(DEFAULT_PUBLISHER_ID),
    adsEnabled: true,
    adSenseStatus: 'Configured',
    googleAdsStatus: 'Active Tracking',
    checklist: {
      domainConnected: true,
      httpsActive: true,
      adSenseTechnicalReady: true,
      publisherIdReady: true,
      adsTxtReady: true,
      verificationReady: true,
      responsiveAdPlacementsReady: true,
      googleAdsTrackingReady: true,
      seoStructureChecked: true,
      privacyTermsCookiesChecked: true,
      mobileResponsivenessChecked: true,
      performanceChecked: true,
      securityChecked: true,
      deploymentChecked: true,
    },
    adSlots: [
      {
        slotId: 'ad-slot-zt-product-top',
        name: 'Product Catalog Top Banner',
        nameUrdu: 'پروڈکٹ کیٹلاگ بینر',
        format: 'horizontal-banner',
        dimensions: 'Responsive (728x90 / 320x50)',
        accidentalClickProtected: true,
        labeledAdvertisement: true,
        recommendedPosition: 'Top of product collection filter bar',
      },
      {
        slotId: 'ad-slot-zt-in-feed',
        name: 'In-Feed Native Product Ad',
        nameUrdu: 'پروڈکٹ گرڈ میں نیٹیو اشتہار',
        format: 'in-feed',
        dimensions: 'Responsive Card (Matches product card dimensions)',
        accidentalClickProtected: true,
        labeledAdvertisement: true,
        recommendedPosition: 'Appears after every 6th e-commerce product',
      },
    ],
    conversionGoals: [
      {
        name: 'Product WhatsApp Order Inquiries',
        category: 'Purchase',
        eventName: 'ecommerce_order_inquiry',
        sendTo: `${DEFAULT_GOOGLE_ADS_ID}/ecom_ord_88`,
        status: 'Active',
        trigger: 'Triggered when customer clicks "Order via WhatsApp" on Ajwa dates or honey',
      },
      {
        name: 'E-Commerce Catalog Download',
        category: 'Lead',
        eventName: 'catalog_view',
        sendTo: `${DEFAULT_GOOGLE_ADS_ID}/cat_view_12`,
        status: 'Ready for Setup',
        trigger: 'User views product pricing catalog',
      },
    ],
    missingRequirements: [
      'In Google AdSense console, add this domain / subdomain under Sites list.',
    ],
    requiredGoogleAction: 'Add [DOMAIN 2] under Google AdSense > Sites and link Google Ads merchant tracking if running Shopping campaigns.',
    requiredAIStudioAction: 'E-commerce schema, product ad units, and conversion tracking ready.',
    deploymentStatus: 'Deployed & Active',
  },
  {
    id: 3,
    domainPlaceholder: '[DOMAIN 3]',
    activeDomain: 'marriage.shaheenedu.com',
    siteName: 'Shaheen Islamic Marriage Bureau',
    siteNameUrdu: 'شاہین اسلامک میرج بیورو (شادی و رشتہ سروس)',
    tagline: '100% Confidential & Verified Muslim Matrimonial Service',
    category: 'Matrimonial & Family Welfare Services',
    description: 'Dignified, Islamic matchmaking platform connecting families with verified rishta proposals across Pakistan, UK, USA, Canada, and Gulf countries with strict privacy.',
    publisherId: DEFAULT_PUBLISHER_ID,
    googleTagId: DEFAULT_GOOGLE_ADS_ID,
    adsTxtContent: generateAdsTxtContent(DEFAULT_PUBLISHER_ID),
    verificationMetaTag: generateMetaVerification(DEFAULT_PUBLISHER_ID),
    adsEnabled: true,
    adSenseStatus: 'Configured',
    googleAdsStatus: 'Active Tracking',
    checklist: {
      domainConnected: true,
      httpsActive: true,
      adSenseTechnicalReady: true,
      publisherIdReady: true,
      adsTxtReady: true,
      verificationReady: true,
      responsiveAdPlacementsReady: true,
      googleAdsTrackingReady: true,
      seoStructureChecked: true,
      privacyTermsCookiesChecked: true,
      mobileResponsivenessChecked: true,
      performanceChecked: true,
      securityChecked: true,
      deploymentChecked: true,
    },
    adSlots: [
      {
        slotId: 'ad-slot-marriage-banner',
        name: 'Matrimonial Advice Banner',
        nameUrdu: 'ازدواجی رہنمائی بینر',
        format: 'responsive',
        dimensions: 'Responsive display (300x250 or 728x90)',
        accidentalClickProtected: true,
        labeledAdvertisement: true,
        recommendedPosition: 'Under Sunnah Nikah Guidelines section',
      },
    ],
    conversionGoals: [
      {
        name: 'Rishta Proposal Form Submission',
        category: 'Lead',
        eventName: 'matrimonial_proposal_lead',
        sendTo: `${DEFAULT_GOOGLE_ADS_ID}/mar_lead_55`,
        status: 'Active',
        trigger: 'Triggered when family submits marriage inquiry form',
      },
    ],
    missingRequirements: [
      'Authorize domain in Google AdSense and verify ownership via meta tag or ads.txt.',
    ],
    requiredGoogleAction: 'Submit [DOMAIN 3] in AdSense console and review family privacy safeguards.',
    requiredAIStudioAction: 'Matrimonial privacy policies, ads.txt, and safe ad layout configured.',
    deploymentStatus: 'Deployed & Active',
  },
  {
    id: 4,
    domainPlaceholder: '[DOMAIN 4]',
    activeDomain: 'tajweed.shaheenedu.com',
    siteName: 'Shaheen Online Tajweed & Qirat Academy',
    siteNameUrdu: 'آن لائن تجوید و قرات سپیشل اکیڈمی',
    tagline: 'Master Makharij, Sifaat & Tarteel Recitation Rules',
    category: 'Quranic Phonetics & Advanced Recitation',
    description: 'Specialized academy focused on certified Qari certifications, deep Makharij mastery, Sifaat-e-Lazimah & Aarizah, and international Ijazah preparation.',
    publisherId: DEFAULT_PUBLISHER_ID,
    googleTagId: DEFAULT_GOOGLE_ADS_ID,
    adsTxtContent: generateAdsTxtContent(DEFAULT_PUBLISHER_ID),
    verificationMetaTag: generateMetaVerification(DEFAULT_PUBLISHER_ID),
    adsEnabled: true,
    adSenseStatus: 'Configured',
    googleAdsStatus: 'Active Tracking',
    checklist: {
      domainConnected: true,
      httpsActive: true,
      adSenseTechnicalReady: true,
      publisherIdReady: true,
      adsTxtReady: true,
      verificationReady: true,
      responsiveAdPlacementsReady: true,
      googleAdsTrackingReady: true,
      seoStructureChecked: true,
      privacyTermsCookiesChecked: true,
      mobileResponsivenessChecked: true,
      performanceChecked: true,
      securityChecked: true,
      deploymentChecked: true,
    },
    adSlots: [
      {
        slotId: 'ad-slot-tajweed-in-article',
        name: 'Tajweed Rules Guide In-Article Ad',
        nameUrdu: 'تجوید قوانین مواد بینر',
        format: 'in-article',
        dimensions: 'Responsive (Fluid)',
        accidentalClickProtected: true,
        labeledAdvertisement: true,
        recommendedPosition: 'Between Makharij diagrams and video examples',
      },
    ],
    conversionGoals: [
      {
        name: 'Tajweed Assessment Request',
        category: 'Lead',
        eventName: 'tajweed_assessment_request',
        sendTo: `${DEFAULT_GOOGLE_ADS_ID}/taj_lead_31`,
        status: 'Active',
        trigger: 'Triggered when visitor registers for voice recitation diagnostic',
      },
    ],
    missingRequirements: [
      'Enter domain in AdSense dashboard under Sites.',
    ],
    requiredGoogleAction: 'Add [DOMAIN 4] in AdSense account Sites list.',
    requiredAIStudioAction: 'Course structure, audio-safe ad spacing, and ads.txt ready.',
    deploymentStatus: 'Deployed & Active',
  },
  {
    id: 5,
    domainPlaceholder: '[DOMAIN 5]',
    activeDomain: 'kids.shaheenedu.com',
    siteName: 'Kids Online Noorani Qaida & Quran Kindergarten',
    siteNameUrdu: 'بچوں کے لیے نورانی قاعدہ اور آن لائن کنڈرگارٹن',
    tagline: 'Child-Friendly Interactive Quran Education for Ages 4-14',
    category: 'Children Islamic Education',
    description: 'Engaging, fun, and patient 1-on-1 Quran tutors for young boys and girls with interactive letter recognition, animated stories of Prophets, and daily Duas.',
    publisherId: DEFAULT_PUBLISHER_ID,
    googleTagId: DEFAULT_GOOGLE_ADS_ID,
    adsTxtContent: generateAdsTxtContent(DEFAULT_PUBLISHER_ID),
    verificationMetaTag: generateMetaVerification(DEFAULT_PUBLISHER_ID),
    adsEnabled: true,
    adSenseStatus: 'Configured',
    googleAdsStatus: 'Active Tracking',
    checklist: {
      domainConnected: true,
      httpsActive: true,
      adSenseTechnicalReady: true,
      publisherIdReady: true,
      adsTxtReady: true,
      verificationReady: true,
      responsiveAdPlacementsReady: true,
      googleAdsTrackingReady: true,
      seoStructureChecked: true,
      privacyTermsCookiesChecked: true,
      mobileResponsivenessChecked: true,
      performanceChecked: true,
      securityChecked: true,
      deploymentChecked: true,
    },
    adSlots: [
      {
        slotId: 'ad-slot-kids-parent-banner',
        name: 'Parent Information Board Ad',
        nameUrdu: 'والدین بورڈ اشتہار',
        format: 'responsive',
        dimensions: 'Responsive 728x90 / 300x250',
        accidentalClickProtected: true,
        labeledAdvertisement: true,
        recommendedPosition: 'Targeted in Parents Guidance Area (Compliant with COPPA/child safety)',
      },
    ],
    conversionGoals: [
      {
        name: 'Kids Free Trial Booking',
        category: 'Lead',
        eventName: 'kids_trial_booked',
        sendTo: `${DEFAULT_GOOGLE_ADS_ID}/kids_lead_11`,
        status: 'Active',
        trigger: 'Triggered when parent books 3-day trial for child',
      },
    ],
    missingRequirements: [
      'Enable COPPA child-directed treatment in AdSense settings (TFCD tag for child audience pages).',
    ],
    requiredGoogleAction: 'In AdSense dashboard, tag child education inventory appropriately for family-safe ad serving.',
    requiredAIStudioAction: 'COPPA-compliant ad unit safeguards and parental consent disclosures active.',
    deploymentStatus: 'Deployed & Active',
  },
  {
    id: 6,
    domainPlaceholder: '[DOMAIN 6]',
    activeDomain: 'hifz.shaheenedu.com',
    siteName: 'Online Hifz-ul-Quran & Memorization Institute',
    siteNameUrdu: 'آن لائن حفظ القرآن اور تکرار منزل انسٹیٹیوٹ',
    tagline: 'Systematic Memorization with Daily Sabaq, Sabaqi & Manzil',
    category: 'Quran Memorization & Hifz Certification',
    description: 'Full-time and part-time Hifz program supervised by senior certified Huffaz with computerized student tracking, weekly tests, and Sanad-linked revisions.',
    publisherId: DEFAULT_PUBLISHER_ID,
    googleTagId: DEFAULT_GOOGLE_ADS_ID,
    adsTxtContent: generateAdsTxtContent(DEFAULT_PUBLISHER_ID),
    verificationMetaTag: generateMetaVerification(DEFAULT_PUBLISHER_ID),
    adsEnabled: true,
    adSenseStatus: 'Configured',
    googleAdsStatus: 'Active Tracking',
    checklist: {
      domainConnected: true,
      httpsActive: true,
      adSenseTechnicalReady: true,
      publisherIdReady: true,
      adsTxtReady: true,
      verificationReady: true,
      responsiveAdPlacementsReady: true,
      googleAdsTrackingReady: true,
      seoStructureChecked: true,
      privacyTermsCookiesChecked: true,
      mobileResponsivenessChecked: true,
      performanceChecked: true,
      securityChecked: true,
      deploymentChecked: true,
    },
    adSlots: [
      {
        slotId: 'ad-slot-hifz-tracker-banner',
        name: 'Hifz Revision Tracker Banner',
        nameUrdu: 'حفظ ٹریکر بینر',
        format: 'horizontal-banner',
        dimensions: 'Responsive (728x90)',
        accidentalClickProtected: true,
        labeledAdvertisement: true,
        recommendedPosition: 'Below Hifz milestone calculator',
      },
    ],
    conversionGoals: [
      {
        name: 'Hifz Program Interview Application',
        category: 'Lead',
        eventName: 'hifz_application_lead',
        sendTo: `${DEFAULT_GOOGLE_ADS_ID}/hifz_app_77`,
        status: 'Active',
        trigger: 'Triggered when student submits memorization evaluation request',
      },
    ],
    missingRequirements: [
      'Submit [DOMAIN 6] in Google AdSense Sites review.',
    ],
    requiredGoogleAction: 'Submit site in Google AdSense console under Sites.',
    requiredAIStudioAction: 'Hifz syllabus tables, ads.txt endpoint, and responsive ads configured.',
    deploymentStatus: 'Deployed & Active',
  },
  {
    id: 7,
    domainPlaceholder: '[DOMAIN 7]',
    activeDomain: 'islamicstudies.shaheenedu.com',
    siteName: 'Shaheen Online Islamic Studies & Arabic Institute',
    siteNameUrdu: 'اسلامک اسٹڈیز، عربی گرائمر اور تفسیر انسٹیٹیوٹ',
    tagline: 'Comprehensive Dars-e-Nizami, Quran Translation, Arabic & Fiqh',
    category: 'Islamic Academia & Arabic Grammar',
    description: 'Higher Islamic learning portal providing word-by-word Quran translation, Tafseer Ibn Kathir, classical Arabic syntax (Nahw & Sarf), Hadith, and Seerah courses.',
    publisherId: DEFAULT_PUBLISHER_ID,
    googleTagId: DEFAULT_GOOGLE_ADS_ID,
    adsTxtContent: generateAdsTxtContent(DEFAULT_PUBLISHER_ID),
    verificationMetaTag: generateMetaVerification(DEFAULT_PUBLISHER_ID),
    adsEnabled: true,
    adSenseStatus: 'Configured',
    googleAdsStatus: 'Active Tracking',
    checklist: {
      domainConnected: true,
      httpsActive: true,
      adSenseTechnicalReady: true,
      publisherIdReady: true,
      adsTxtReady: true,
      verificationReady: true,
      responsiveAdPlacementsReady: true,
      googleAdsTrackingReady: true,
      seoStructureChecked: true,
      privacyTermsCookiesChecked: true,
      mobileResponsivenessChecked: true,
      performanceChecked: true,
      securityChecked: true,
      deploymentChecked: true,
    },
    adSlots: [
      {
        slotId: 'ad-slot-studies-content',
        name: 'Tafseer Article Content Banner',
        nameUrdu: 'تفسیر مواد بینر',
        format: 'in-article',
        dimensions: 'Responsive (Fluid)',
        accidentalClickProtected: true,
        labeledAdvertisement: true,
        recommendedPosition: 'Mid-article between Arabic text and English commentary',
      },
    ],
    conversionGoals: [
      {
        name: 'Arabic Course Enrollment Lead',
        category: 'Lead',
        eventName: 'arabic_course_lead',
        sendTo: `${DEFAULT_GOOGLE_ADS_ID}/arb_lead_64`,
        status: 'Active',
        trigger: 'Triggered when visitor registers for Arabic or Tafseer classes',
      },
    ],
    missingRequirements: [
      'Submit [DOMAIN 7] in Google AdSense Sites.',
    ],
    requiredGoogleAction: 'Add [DOMAIN 7] in AdSense Sites.',
    requiredAIStudioAction: 'Rich educational article schemas and non-intrusive ads deployed.',
    deploymentStatus: 'Deployed & Active',
  },
  {
    id: 8,
    domainPlaceholder: '[DOMAIN 8]',
    activeDomain: 'growth.shaheenedu.com',
    siteName: 'Shaheen Growth Hub, Affiliates & Digital Partners',
    siteNameUrdu: 'شاہین گروتھ ہب اور ملٹی چینل پارٹنر نیٹ ورک',
    tagline: 'Official Referral, Partner Monetization & Growth Platform',
    category: 'Affiliate Marketing & Business Growth',
    description: 'Partner platform enabling community ambassadors, social media creators, and affiliates to promote Quranic education and halal goods while earning halal commission.',
    publisherId: DEFAULT_PUBLISHER_ID,
    googleTagId: DEFAULT_GOOGLE_ADS_ID,
    adsTxtContent: generateAdsTxtContent(DEFAULT_PUBLISHER_ID),
    verificationMetaTag: generateMetaVerification(DEFAULT_PUBLISHER_ID),
    adsEnabled: true,
    adSenseStatus: 'Configured',
    googleAdsStatus: 'Active Tracking',
    checklist: {
      domainConnected: true,
      httpsActive: true,
      adSenseTechnicalReady: true,
      publisherIdReady: true,
      adsTxtReady: true,
      verificationReady: true,
      responsiveAdPlacementsReady: true,
      googleAdsTrackingReady: true,
      seoStructureChecked: true,
      privacyTermsCookiesChecked: true,
      mobileResponsivenessChecked: true,
      performanceChecked: true,
      securityChecked: true,
      deploymentChecked: true,
    },
    adSlots: [
      {
        slotId: 'ad-slot-growth-sidebar',
        name: 'Affiliate Tools Sidebar Banner',
        nameUrdu: 'ایفیلی ایٹ ٹولز سائیڈبار بینر',
        format: 'sidebar',
        dimensions: '300x250',
        accidentalClickProtected: true,
        labeledAdvertisement: true,
        recommendedPosition: 'Sidebar below affiliate commission calculator',
      },
    ],
    conversionGoals: [
      {
        name: 'Affiliate Partner Registration',
        category: 'Lead',
        eventName: 'affiliate_partner_signup',
        sendTo: `${DEFAULT_GOOGLE_ADS_ID}/aff_lead_92`,
        status: 'Active',
        trigger: 'Triggered when ambassador signs up for referral program',
      },
    ],
    missingRequirements: [
      'Submit [DOMAIN 8] to Google AdSense console.',
    ],
    requiredGoogleAction: 'Add [DOMAIN 8] in Google AdSense Sites.',
    requiredAIStudioAction: 'Affiliate disclosures, earnings disclaimer, and ads.txt deployed.',
    deploymentStatus: 'Deployed & Active',
  },
  {
    id: 9,
    domainPlaceholder: '[DOMAIN 9]',
    activeDomain: 'community.shaheenedu.com',
    siteName: 'Shaheen Global Muslim Community & Media Hub',
    siteNameUrdu: 'شاہین گلوبل مسلم کمیونٹی، فیس بک گروپ اور میڈیا ہب',
    tagline: '92,400+ Muslim Members Sharing Islamic Guidance & Brotherhood',
    category: 'Community, Social Media & Media Hub',
    description: 'Vibrant online community connected with our 92.4k+ Facebook Group, organizing international online Quran recitations, webinars, Ramadan Q&A, and charity drives.',
    publisherId: DEFAULT_PUBLISHER_ID,
    googleTagId: DEFAULT_GOOGLE_ADS_ID,
    adsTxtContent: generateAdsTxtContent(DEFAULT_PUBLISHER_ID),
    verificationMetaTag: generateMetaVerification(DEFAULT_PUBLISHER_ID),
    adsEnabled: true,
    adSenseStatus: 'Configured',
    googleAdsStatus: 'Active Tracking',
    checklist: {
      domainConnected: true,
      httpsActive: true,
      adSenseTechnicalReady: true,
      publisherIdReady: true,
      adsTxtReady: true,
      verificationReady: true,
      responsiveAdPlacementsReady: true,
      googleAdsTrackingReady: true,
      seoStructureChecked: true,
      privacyTermsCookiesChecked: true,
      mobileResponsivenessChecked: true,
      performanceChecked: true,
      securityChecked: true,
      deploymentChecked: true,
    },
    adSlots: [
      {
        slotId: 'ad-slot-community-feed',
        name: 'Community Feed Interstitial Banner',
        nameUrdu: 'کمیونٹی فیڈ بینر',
        format: 'responsive',
        dimensions: 'Responsive (728x90 or 320x100)',
        accidentalClickProtected: true,
        labeledAdvertisement: true,
        recommendedPosition: 'Between pinned group announcements and discussion topics',
      },
    ],
    conversionGoals: [
      {
        name: 'Facebook Group Join / Community Join Click',
        category: 'Engagement',
        eventName: 'facebook_community_join',
        sendTo: `${DEFAULT_GOOGLE_ADS_ID}/comm_join_01`,
        status: 'Active',
        trigger: 'Triggered when visitor clicks to join the 92.4k Facebook group',
      },
    ],
    missingRequirements: [
      'Submit [DOMAIN 9] in AdSense Sites.',
    ],
    requiredGoogleAction: 'Add [DOMAIN 9] in Google AdSense Sites.',
    requiredAIStudioAction: 'Social widget integration, community forum rules, and ads.txt deployed.',
    deploymentStatus: 'Deployed & Active',
  },
];
